// Copyright (c) Middleman Software, Inc. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root.

using Middleman.PdfFlex.Styling;

namespace Middleman.PdfFlex.Elements;

/// <summary>
/// Configuration for the appearance of a table of contents generated by <see cref="TocBuilder"/>.
/// Controls indentation and per-level font styling.
/// </summary>
public class TocStyle
{
    /// <summary>
    /// Gets or sets the indentation in points applied per heading level.
    /// For example, H2 entries are indented by this value, H3 by twice this value, etc.
    /// Defaults to 20.
    /// </summary>
    public double IndentPerLevel { get; set; } = 20;

    /// <summary>
    /// Gets or sets an optional font specification per heading level (1-6).
    /// When a level is not present in the dictionary, the default document font is used.
    /// </summary>
    public Dictionary<int, FontSpec>? FontPerLevel { get; set; }
}
