// Copyright (c) Middleman Software, Inc. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root.

namespace Middleman.PdfFlex.Internal
{
    /// <summary>
    /// PdfFlex message ID.
    /// Represents IDs for error and diagnostic messages generated by PdfFlex.
    /// </summary>
    // ReSharper disable once InconsistentNaming
    enum PsMsgId
    {
        None = 0,

        // ----- General Messages ---------------------------------------------------------------------

        /// <summary>
        /// PSMsgID.
        /// </summary>
        SampleMessage1 = MessageIdOffset.Ps,

        /// <summary>
        /// PSMsgID.
        /// </summary>
        SampleMessage2,

        // ----- XGraphics Messages ---------------------------------------------------------------

        // ----- PDF Messages ----------------------------------------------------------------------

        /// <summary>
        /// PSMsgID.
        /// </summary>
        NameMustStartWithSlash,

        /// <summary>
        /// PSMsgID.
        /// </summary>
        UserOrOwnerPasswordRequired,

        // ----- PdfParser Messages -------------------------------------------------------------------

        /// <summary>
        /// PSMsgID.
        /// </summary>
        UnexpectedToken,

        /// <summary>
        /// PSMsgID.
        /// </summary>
        UnknownEncryption,
    }
}
